### ISSUE TITLE
Nim backend

### ISSUE THREAD

**Issue by hartsantler** [rusthon/Rusthon#45]
This could help for making human readable wrappers around C code, at which point readability is mostly lost in the generated code anyways.  Nim could have issues with GC and threads, but where the user needs threads they can instead use Rusthon C++ backend.

"Nim is designed to use soft realtime GC on thread local heaps. This means that a thread cannot touch the memory of another thread. If you add to this the necessary level of indirection of calling Nim from a different programming language (or vice versa), the amount of barriers to jump over to do what in other unsafe languages is just accessing a variable starts to pile up." - Grzegorz Adam Hankiewicz

**Comment by hartsantler** [comment]
```bash
brett@mint15 ~/Rusthon $ ./rusthon.py ./examples/hello_nim.md 
config/nim.cfg(45, 2) Hint: added path: '/home/brett/.babel/pkgs/' [Path]
config/nim.cfg(46, 2) Hint: added path: '/home/brett/.nimble/pkgs/' [Path]
Hint: used config file '/home/brett/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: rusthon_build [Processing]
CC: rusthon_build
[Linking]
Hint: operation successful (8757 lines compiled; 0.198 sec total; 14.148MB) [SuccessX]
g++ -O3 -fprofile-generate -march=native -mtune=native /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11 -static -L/tmp/. -lrusthon_build.nim
/tmp/./librusthon_build.nim.a(rusthon_build.o): In function `main':
rusthon_build.c:(.text+0x25c): multiple definition of `main'
/tmp/ccP6IPMB.o:rusthon-c++-build.cpp:(.text.startup+0x0): first defined here
/tmp/./librusthon_build.nim.a(stdlib_system.o): In function `nimUnloadLibrary':
stdlib_system.c:(.text+0xffd6): undefined reference to `dlclose'
/tmp/./librusthon_build.nim.a(stdlib_system.o): In function `nimLoadLibrary':
stdlib_system.c:(.text+0x10001): undefined reference to `dlopen'
/tmp/./librusthon_build.nim.a(stdlib_system.o): In function `nimGetProcAddr':
stdlib_system.c:(.text+0x10036): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "./rusthon.py", line 684, in <module>
    main()
  File "./rusthon.py", line 639, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "./rusthon.py", line 528, in build
    subprocess.check_call( cmd )
  File "/usr/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['g++', '-O3', '-fprofile-generate', '-march=native', '-mtune=native', '/tmp/rusthon-c++-build.cpp', '-o', '/tmp/rusthon-c++-bin', '-pthread', '-std=c++11', '-static', '-L/tmp/.', '-lrusthon_build.nim']' returned non-zero exit status 1
```

**Comment by hartsantler** [comment]
why is nim not linking to `libdl`?
```python
brett@mint15 ~/Rusthon $ ./rusthon.py ./examples/hello_nim.md 
config/nim.cfg(45, 2) Hint: added path: '/home/brett/.babel/pkgs/' [Path]
config/nim.cfg(46, 2) Hint: added path: '/home/brett/.nimble/pkgs/' [Path]
Hint: used config file '/home/brett/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: rusthon_build [Processing]
[Linking]
Hint: operation successful (8756 lines compiled; 0.164 sec total; 14.148MB) [SuccessX]
g++ -O3 -fprofile-generate -march=native -mtune=native /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11 -static -L/tmp/. -ldl -lrusthon_build.nim
/tmp/./librusthon_build.nim.a(stdlib_system.o): In function `nimUnloadLibrary':
stdlib_system.c:(.text+0xffd6): undefined reference to `dlclose'
/tmp/./librusthon_build.nim.a(stdlib_system.o): In function `nimLoadLibrary':
stdlib_system.c:(.text+0x10001): undefined reference to `dlopen'
/tmp/./librusthon_build.nim.a(stdlib_system.o): In function `nimGetProcAddr':
stdlib_system.c:(.text+0x10036): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "./rusthon.py", line 689, in <module>
    main()
  File "./rusthon.py", line 644, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "./rusthon.py", line 533, in build
    subprocess.check_call( cmd )
  File "/usr/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['g++', '-O3', '-fprofile-generate', '-march=native', '-mtune=native', '/tmp/rusthon-c++-build.cpp', '-o', '/tmp/rusthon-c++-bin', '-pthread', '-std=c++11', '-static', '-L/tmp/.', '-ldl', '-lrusthon_build.nim']' returned non-zero exit status 1
```

**Comment by hartsantler** [comment]
i have fixed all the above problems by bypassing the Nim compiler and just using it to generate C code, which then gets hacked up a little and merged into a single C file, that then gets compiled to a static library that is linked to the final exe.

NimMain() must be called by the user to setup GC.  TODO a fake `nim` module.
https://github.com/rusthon/Rusthon/commit/ab89bc0f519a104918d8f217bbf640868688b7c3

**Comment by hartsantler** [comment]
__TODO__ parse the nim code in markdown and generate the wrapper code that is currently hand written like this:
```rusthon
with extern(abi="C"):
	def my_nim_function( a:int, b:int ) -> int:
		pass
```

**Comment by hartsantler** [comment]
basic wrapper generator is working now so rusthon code can simply call any nim functions that are exported to C.

__TODO__ 
* nim functions that do not return anything, 
* test `GC_ref`
* return cstring, needs to be converted to a std::string

**Comment by hartsantler** [comment]
the nim code is no longer hacked into a single file and custom built, instead Nim itself is used to generate a shared library, that is then linked into the final c++ exe.
https://github.com/rusthon/Rusthon/commit/b1425ea9621ca6981898471be01b0156e4ccc0b2
