### ISSUE TITLE
Java frontend

### ISSUE THREAD

**Issue by hartsantler** [rusthon/Rusthon#46]
this fork of java2python will output Rusthon's syntax.
https://github.com/rusthon/java2python

**Comment by hartsantler** [comment]
the option --rusthon can now be given to j2py to output Rusthon syntax.
https://github.com/rusthon/java2python/commit/04d02c1593eafb82a55cc55eae8673e6b41cde07

**Comment by hartsantler** [comment]
This fork of j2c will repackage it as a command line tool.  j2c is a more direct way to translate to c++, it should be an option where java2python fails.
https://github.com/rusthon/j2c

**Comment by hartsantler** [comment]
testing translating the deeplearning4java framework in this fork.
https://github.com/rusthon/deeplearning4j

**Comment by hartsantler** [comment]
java2python using the old Antlr may not support new libraries like deeplearning4j, the hacks i put into java2python to get it to work with deeplearning4j may not be safe. also generates ugly `Runtime._exec(hacks)`.

JavaLang
------------
a better solution looks like JavaLang by Chris Thunes which parses java7 into an AST.
forked here:
https://github.com/rusthon/javalang

**Comment by hartsantler** [comment]
java in the markdown should be compiled by default using `javac` and make g++ link to jvm in the final exe.

xml in the markdown tagged with `@giws` will trigger wrappers to be generated with Giws (reverse Swig):
https://github.com/opencollab/giws

**Comment by hartsantler** [comment]
this fixes linking to libjvm.so https://github.com/rusthon/Rusthon/commit/37c6d1d9e5a744158ee3e5f4ad8605bb633fef76
but now there is this error when running the test:
```
g++ -O3 -fprofile-generate -march=native -mtune=native /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11 -ljvm -I/usr/lib/jvm/java-7-oracle/include -I/usr/lib/jvm/java-7-oracle/include/linux -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64 -L/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/
running: /tmp/rusthon-c++-bin
Could not get the Class mymodule/MyJavaClass
Exception in thread "main" java.lang.NoClassDefFoundError: mymodule/MyJavaClass
Caused by: java.lang.ClassNotFoundException: mymodule.MyJavaClass
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

```

**Comment by hartsantler** [comment]
hello world now works using giws.
https://github.com/rusthon/Rusthon/commit/36c0df7f83e2bd68922172cf6e68c3df992c5059

new syntax
-------------
this enables the JavaVM
```python
import jvm
```
this creates a new Java Object
```python
a = jvm(SomeJavaClass())
```

**Comment by hartsantler** [comment]
new fork of Giws to support properties being worked on here:
https://github.com/rusthon/giws
