### ISSUE TITLE
Nuitka Integration

### ISSUE THREAD

**Issue by hartsantler** [rusthon/Rusthon#52]
call into libpython with Nuitka.
https://github.com/rusthon/Rusthon/commit/dfbc72e4ea993ff41ac0e1f6a239a8150e281d90
https://github.com/rusthon/Rusthon/commit/1624da9f6499ad6b8bab15835b5fd44059659f4d
https://github.com/rusthon/Rusthon/commit/f472ac17578a6aa9022e5a2a7627ed17b48388b1
https://github.com/rusthon/Rusthon/commit/753edac31c37cc4cec8b01934559646784d91b21

**Comment by hartsantler** [comment]
missing some include:
```bash
g++ -O3 -fprofile-generate -march=native -mtune=native -I/tmp -I/usr/local/lib/python2.7/dist-packages/nuitka/build/include -I/usr/include/python2.7 -lpython2.7 /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11
/tmp/ccH4h241.o: In function `RESTORE_ERROR_OCCURRED(_object*, _object*, _traceback*)':
rusthon-c++-build.cpp:(.text+0x9): undefined reference to `_PyThreadState_Current'
/tmp/ccH4h241.o: In function `DROP_ERROR_OCCURRED()':
rusthon-c++-build.cpp:(.text+0x133): undefined reference to `_PyThreadState_Current'
/tmp/ccH4h241.o: In function `isFrameUnusable(_frame*)':
rusthon-c++-build.cpp:(.text+0x29b): undefined reference to `_PyThreadState_Current'
/tmp/ccH4h241.o: In function `GET_STRING_DICT_ENTRY(_dictobject*, PyStringObject*)':
rusthon-c++-build.cpp:(.text+0x2fc): undefined reference to `PyDict_Type'
rusthon-c++-build.cpp:(.text+0x363): undefined reference to `PyString_Type'
/tmp/ccH4h241.o: In function `createGlobalConstants()':
rusthon-c++-build.cpp:(.text+0xb2d): undefined reference to `PyCObject_FromVoidPtr'
rusthon-c++-build.cpp:(.text+0xb54): undefined reference to `_PyDict_NewPresized'
rusthon-c++-build.cpp:(.text+0xb6b): undefined reference to `PyDict_Size'
rusthon-c++-build.cpp:(.text+0xb83): undefined reference to `PyInt_FromLong'
rusthon-c++-build.cpp:(.text+0xb9c): undefined reference to `PyInt_FromLong'
rusthon-c++-build.cpp:(.text+0xbb9): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xbdc): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xbff): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xc22): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xc45): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
/tmp/ccH4h241.o:rusthon-c++-build.cpp:(.text+0xc68): more undefined references to `UNSTREAM_STRING(unsigned char const*, long, bool)' follow
/tmp/ccH4h241.o: In function `createGlobalConstants()':
rusthon-c++-build.cpp:(.text+0x1052): undefined reference to `PyTuple_New'
/tmp/ccH4h241.o: In function `MAKE_TUPLE(_object**, long)':
rusthon-c++-build.cpp:(.text+0x15d8): undefined reference to `PyTuple_New'
/tmp/ccH4h241.o: In function `CALL_FUNCTION(_object*, _object*, _object*) [clone .constprop.95]':
rusthon-c++-build.cpp:(.text+0x1dab): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x1e07): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x1e3f): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x1eb3): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x1ed8): undefined reference to `PyExc_SystemError'
rusthon-c++-build.cpp:(.text+0x1eec): undefined reference to `PyErr_Format'
rusthon-c++-build.cpp:(.text+0x1f04): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x1f1a): undefined reference to `PyErr_Format'
/tmp/ccH4h241.o: In function `CALL_FUNCTION_WITH_ARGS1(_object*, _object*)':
rusthon-c++-build.cpp:(.text+0x214b): undefined reference to `Nuitka_Function_Type'
rusthon-c++-build.cpp:(.text+0x2157): undefined reference to `Nuitka_Method_Type'
rusthon-c++-build.cpp:(.text+0x2163): undefined reference to `PyCFunction_Type'
rusthon-c++-build.cpp:(.text+0x2177): undefined reference to `PyFunction_Type'
rusthon-c++-build.cpp:(.text+0x2203): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x220f): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x225e): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x229c): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x22a8): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x22fd): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2453): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x2485): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x24c2): undefined reference to `callPythonFunction(_object*, _object**, int)'
rusthon-c++-build.cpp:(.text+0x2595): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x25ac): undefined reference to `PyErr_Format'
/tmp/ccH4h241.o: In function `CALL_FUNCTION_WITH_ARGS2(_object*, _object*, _object*)':
rusthon-c++-build.cpp:(.text+0x271d): undefined reference to `Nuitka_Function_Type'
rusthon-c++-build.cpp:(.text+0x2729): undefined reference to `Nuitka_Method_Type'
rusthon-c++-build.cpp:(.text+0x2735): undefined reference to `PyCFunction_Type'
rusthon-c++-build.cpp:(.text+0x2749): undefined reference to `PyFunction_Type'
rusthon-c++-build.cpp:(.text+0x27fb): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2807): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x285e): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2898): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x28a4): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x2901): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2a11): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x2a49): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x2a90): undefined reference to `callPythonFunction(_object*, _object**, int)'
rusthon-c++-build.cpp:(.text+0x2b2d): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x2b44): undefined reference to `PyErr_Format'
rusthon-c++-build.cpp:(.text+0x2b5b): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x2b72): undefined reference to `PyErr_Format'
/tmp/ccH4h241.o: In function `CALL_FUNCTION_WITH_ARGS3(_object*, _object*, _object*, _object*)':
rusthon-c++-build.cpp:(.text+0x2d33): undefined reference to `Nuitka_Function_Type'
rusthon-c++-build.cpp:(.text+0x2d3f): undefined reference to `Nuitka_Method_Type'
rusthon-c++-build.cpp:(.text+0x2d4b): undefined reference to `PyCFunction_Type'
rusthon-c++-build.cpp:(.text+0x2d5f): undefined reference to `PyFunction_Type'
rusthon-c++-build.cpp:(.text+0x2e1b): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2e27): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x2e83): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2eb8): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x2ec4): undefined reference to `_Py_CheckRecursionLimit'
rusthon-c++-build.cpp:(.text+0x2f42): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x3059): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x3091): undefined reference to `_Py_CheckRecursiveCall'
rusthon-c++-build.cpp:(.text+0x30e5): undefined reference to `callPythonFunction(_object*, _object**, int)'
rusthon-c++-build.cpp:(.text+0x3182): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x3199): undefined reference to `PyErr_Format'
rusthon-c++-build.cpp:(.text+0x31b0): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x31c7): undefined reference to `PyErr_Format'
/tmp/ccH4h241.o: In function `init__main__':
rusthon-c++-build.cpp:(.text+0x3384): undefined reference to `PyInt_FromLong'
rusthon-c++-build.cpp:(.text+0x33a2): undefined reference to `UNSTREAM_CHAR(unsigned char, bool)'
rusthon-c++-build.cpp:(.text+0x33c5): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x33e8): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x3408): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x3421): undefined reference to `PyTuple_New'
rusthon-c++-build.cpp:(.text+0x3450): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x3490): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x34ca): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x3501): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x352e): undefined reference to `Py_InitModule4_64'
rusthon-c++-build.cpp:(.text+0x355a): undefined reference to `PyModule_GetDict'
rusthon-c++-build.cpp:(.text+0x3574): undefined reference to `PyDict_GetItem'
rusthon-c++-build.cpp:(.text+0x3598): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x35fc): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x36d6): undefined reference to `IMPORT_MODULE(_object*, _object*, _object*, _object*, _object*)'
rusthon-c++-build.cpp:(.text+0x3704): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x3755): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x376a): undefined reference to `Nuitka_Function_New(_object* (*)(Nuitka_FunctionObject*, _object**, long, _object*), _object* (*)(Nuitka_FunctionObject*, _object**, int), _object*, PyCodeObject*, _object*, _object*, _object*)'
rusthon-c++-build.cpp:(.text+0x37c3): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x37d8): undefined reference to `Nuitka_Function_New(_object* (*)(Nuitka_FunctionObject*, _object**, long, _object*), _object* (*)(Nuitka_FunctionObject*, _object**, int), _object*, PyCodeObject*, _object*, _object*, _object*)'
rusthon-c++-build.cpp:(.text+0x380e): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x38e3): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x395a): undefined reference to `PyTraceBack_Type'
rusthon-c++-build.cpp:(.text+0x396f): undefined reference to `_PyObject_GC_New'
rusthon-c++-build.cpp:(.text+0x39b4): undefined reference to `Py_FatalError'
rusthon-c++-build.cpp:(.text+0x39cb): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x39d6): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x39e8): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x39ff): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x3ae3): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x3bb3): undefined reference to `builtin_module'
rusthon-c++-build.cpp:(.text+0x3bc0): undefined reference to `PyModule_GetDict'
rusthon-c++-build.cpp:(.text+0x3bda): undefined reference to `PyDict_SetItem'
rusthon-c++-build.cpp:(.text+0x3c13): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x3cd1): undefined reference to `PyTraceBack_Type'
rusthon-c++-build.cpp:(.text+0x3ce6): undefined reference to `_PyObject_GC_New'
rusthon-c++-build.cpp:(.text+0x3d2b): undefined reference to `Py_FatalError'
rusthon-c++-build.cpp:(.text+0x3d42): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x3d4d): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x3d5f): undefined reference to `_PyGC_generation0'
/tmp/ccH4h241.o: In function `impl_function_1_foo_of___main__(Nuitka_FunctionObject*) [clone .isra.8]':
rusthon-c++-build.cpp:(.text+0x56f8): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x574a): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x57b5): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x5876): undefined reference to `PRINT_ITEM(_object*)'
rusthon-c++-build.cpp:(.text+0x5885): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x58dc): undefined reference to `PyTraceBack_Type'
rusthon-c++-build.cpp:(.text+0x58f1): undefined reference to `_PyObject_GC_New'
rusthon-c++-build.cpp:(.text+0x5936): undefined reference to `Py_FatalError'
rusthon-c++-build.cpp:(.text+0x594d): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x5958): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x596a): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x597f): undefined reference to `PyDict_New'
rusthon-c++-build.cpp:(.text+0x5992): undefined reference to `detachFrame(_traceback*, _object*)'
rusthon-c++-build.cpp:(.text+0x5999): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x5a51): undefined reference to `PRINT_NEW_LINE()'
rusthon-c++-build.cpp:(.text+0x5a60): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x5b23): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x5b77): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x5b85): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x5ba1): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x5bb1): undefined reference to `PyTraceBack_Type'
rusthon-c++-build.cpp:(.text+0x5bc6): undefined reference to `_PyObject_GC_New'
rusthon-c++-build.cpp:(.text+0x5c0b): undefined reference to `Py_FatalError'
rusthon-c++-build.cpp:(.text+0x5c22): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x5c2d): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x5c3f): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x5cc3): undefined reference to `_PyThreadState_Current'
/tmp/ccH4h241.o: In function `fparse_function_1_foo_of___main__(Nuitka_FunctionObject*, _object**, long, _object*)':
rusthon-c++-build.cpp:(.text+0x5ee8): undefined reference to `PyDict_Size'
rusthon-c++-build.cpp:(.text+0x5f30): undefined reference to `ERROR_NO_ARGUMENTS_ALLOWED(Nuitka_FunctionObject*, long)'
/tmp/ccH4h241.o: In function `dparse_function_1_foo_of___main__(Nuitka_FunctionObject*, _object**, int)':
rusthon-c++-build.cpp:(.text+0x6046): undefined reference to `ERROR_NO_ARGUMENTS_ALLOWED(Nuitka_FunctionObject*, long)'
/tmp/ccH4h241.o: In function `impl_function_2_bar_of___main__(Nuitka_FunctionObject*, _object*) [clone .isra.9]':
rusthon-c++-build.cpp:(.text+0x6074): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x60d2): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x613d): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x61fa): undefined reference to `PyObject_Str'
rusthon-c++-build.cpp:(.text+0x6216): undefined reference to `PRINT_ITEM(_object*)'
rusthon-c++-build.cpp:(.text+0x6236): undefined reference to `PRINT_NEW_LINE()'
rusthon-c++-build.cpp:(.text+0x6245): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x62a4): undefined reference to `PyTraceBack_Type'
rusthon-c++-build.cpp:(.text+0x62b9): undefined reference to `_PyObject_GC_New'
rusthon-c++-build.cpp:(.text+0x6302): undefined reference to `Py_FatalError'
rusthon-c++-build.cpp:(.text+0x631d): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x6328): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x633a): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x634f): undefined reference to `PyDict_New'
rusthon-c++-build.cpp:(.text+0x6379): undefined reference to `PyDict_SetItem'
rusthon-c++-build.cpp:(.text+0x6395): undefined reference to `detachFrame(_traceback*, _object*)'
rusthon-c++-build.cpp:(.text+0x639c): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x6493): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x64f3): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x6597): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x6653): undefined reference to `_PyThreadState_Current'
rusthon-c++-build.cpp:(.text+0x66d3): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x66e9): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x6761): undefined reference to `PyTraceBack_Type'
rusthon-c++-build.cpp:(.text+0x6776): undefined reference to `_PyObject_GC_New'
rusthon-c++-build.cpp:(.text+0x67bb): undefined reference to `Py_FatalError'
rusthon-c++-build.cpp:(.text+0x67d2): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x67dd): undefined reference to `_PyGC_generation0'
rusthon-c++-build.cpp:(.text+0x67ef): undefined reference to `_PyGC_generation0'
/tmp/ccH4h241.o: In function `fparse_function_2_bar_of___main__(Nuitka_FunctionObject*, _object**, long, _object*)':
rusthon-c++-build.cpp:(.text+0x6ad2): undefined reference to `PyDict_Size'
rusthon-c++-build.cpp:(.text+0x6b13): undefined reference to `PyDict_Next'
rusthon-c++-build.cpp:(.text+0x6b8c): undefined reference to `MY_RICHCOMPARE(_object*, _object*, int)'
rusthon-c++-build.cpp:(.text+0x6baf): undefined reference to `_Py_TrueStruct'
rusthon-c++-build.cpp:(.text+0x6bc4): undefined reference to `_Py_ZeroStruct'
rusthon-c++-build.cpp:(.text+0x6bd9): undefined reference to `_Py_NoneStruct'
rusthon-c++-build.cpp:(.text+0x6d48): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x6d54): undefined reference to `PyErr_Format'
rusthon-c++-build.cpp:(.text+0x6dd9): undefined reference to `PyString_AsString'
rusthon-c++-build.cpp:(.text+0x702e): undefined reference to `PyExc_TypeError'
rusthon-c++-build.cpp:(.text+0x703a): undefined reference to `PyErr_Format'
rusthon-c++-build.cpp:(.text+0x70b6): undefined reference to `ERROR_MULTIPLE_VALUES(Nuitka_FunctionObject*, long)'
rusthon-c++-build.cpp:(.text+0x711a): undefined reference to `ERROR_TOO_MANY_ARGUMENTS(Nuitka_FunctionObject*, long)'
rusthon-c++-build.cpp:(.text+0x7190): undefined reference to `ERROR_TOO_FEW_ARGUMENTS(Nuitka_FunctionObject*, long)'
/tmp/ccH4h241.o: In function `DICT_SET_ITEM(_object*, _object*, _object*)':
rusthon-c++-build.cpp:(.text.unlikely+0xe7): undefined reference to `PyDict_SetItem'

```

**Comment by hartsantler** [comment]
The things that are `undefined reference` are marked as `extern` in Nuitka's source.
```bash
g++ -O3 -fprofile-generate -march=native -mtune=native -I/tmp -I/usr/local/lib/python2.7/dist-packages/nuitka/build/include /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11 -I/usr/include/python2.7 -lpython2.7
/tmp/ccb5gboe.o: In function `createGlobalConstants()':
rusthon-c++-build.cpp:(.text+0xd09): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xd2c): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xd4f): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xd72): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0xd95): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
/tmp/ccb5gboe.o:rusthon-c++-build.cpp:(.text+0xdb8): more undefined references to `UNSTREAM_STRING(unsigned char const*, long, bool)' follow
/tmp/ccb5gboe.o: In function `CALL_FUNCTION_WITH_ARGS1(_object*, _object*)':
rusthon-c++-build.cpp:(.text+0x236b): undefined reference to `Nuitka_Function_Type'
rusthon-c++-build.cpp:(.text+0x2377): undefined reference to `Nuitka_Method_Type'
rusthon-c++-build.cpp:(.text+0x26e2): undefined reference to `callPythonFunction(_object*, _object**, int)'
/tmp/ccb5gboe.o: In function `CALL_FUNCTION_WITH_ARGS2(_object*, _object*, _object*)':
rusthon-c++-build.cpp:(.text+0x293d): undefined reference to `Nuitka_Function_Type'
rusthon-c++-build.cpp:(.text+0x2949): undefined reference to `Nuitka_Method_Type'
rusthon-c++-build.cpp:(.text+0x2cb0): undefined reference to `callPythonFunction(_object*, _object**, int)'
/tmp/ccb5gboe.o: In function `CALL_FUNCTION_WITH_ARGS3(_object*, _object*, _object*, _object*)':
rusthon-c++-build.cpp:(.text+0x2f53): undefined reference to `Nuitka_Function_Type'
rusthon-c++-build.cpp:(.text+0x2f5f): undefined reference to `Nuitka_Method_Type'
rusthon-c++-build.cpp:(.text+0x3305): undefined reference to `callPythonFunction(_object*, _object**, int)'
/tmp/ccb5gboe.o: In function `impl_function_1_pymethod_of_class_1_A_of___main__(Nuitka_FunctionObject*, _object*) [clone .isra.8]':
rusthon-c++-build.cpp:(.text+0x4b02): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x4b44): undefined reference to `PRINT_ITEM(_object*)'
rusthon-c++-build.cpp:(.text+0x4c9b): undefined reference to `detachFrame(_traceback*, _object*)'
rusthon-c++-build.cpp:(.text+0x4da1): undefined reference to `PRINT_NEW_LINE()'
/tmp/ccb5gboe.o: In function `fparse_function_1_pymethod_of_class_1_A_of___main__(Nuitka_FunctionObject*, _object**, long, _object*)':
rusthon-c++-build.cpp:(.text+0x525c): undefined reference to `MY_RICHCOMPARE(_object*, _object*, int)'
rusthon-c++-build.cpp:(.text+0x5786): undefined reference to `ERROR_MULTIPLE_VALUES(Nuitka_FunctionObject*, long)'
rusthon-c++-build.cpp:(.text+0x57ea): undefined reference to `ERROR_TOO_MANY_ARGUMENTS(Nuitka_FunctionObject*, long)'
rusthon-c++-build.cpp:(.text+0x5860): undefined reference to `ERROR_TOO_FEW_ARGUMENTS(Nuitka_FunctionObject*, long)'
/tmp/ccb5gboe.o: In function `impl_function_2_foo_of___main__(Nuitka_FunctionObject*) [clone .isra.9]':
rusthon-c++-build.cpp:(.text+0x59fa): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x5a3c): undefined reference to `PRINT_ITEM(_object*)'
rusthon-c++-build.cpp:(.text+0x5b58): undefined reference to `detachFrame(_traceback*, _object*)'
rusthon-c++-build.cpp:(.text+0x5c19): undefined reference to `PRINT_NEW_LINE()'
rusthon-c++-build.cpp:(.text+0x5d30): undefined reference to `CALL_FUNCTION_NO_ARGS(_object*)'
rusthon-c++-build.cpp:(.text+0x5e20): undefined reference to `dict_builtin'
rusthon-c++-build.cpp:(.text+0x5e76): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
/tmp/ccb5gboe.o: In function `fparse_function_2_foo_of___main__(Nuitka_FunctionObject*, _object**, long, _object*)':
rusthon-c++-build.cpp:(.text+0x60a0): undefined reference to `ERROR_NO_ARGUMENTS_ALLOWED(Nuitka_FunctionObject*, long)'
/tmp/ccb5gboe.o: In function `dparse_function_2_foo_of___main__(Nuitka_FunctionObject*, _object**, int)':
rusthon-c++-build.cpp:(.text+0x61b6): undefined reference to `ERROR_NO_ARGUMENTS_ALLOWED(Nuitka_FunctionObject*, long)'
/tmp/ccb5gboe.o: In function `init__main__':
rusthon-c++-build.cpp:(.text+0x6242): undefined reference to `UNSTREAM_CHAR(unsigned char, bool)'
rusthon-c++-build.cpp:(.text+0x6265): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x6288): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x62a8): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x62cb): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
rusthon-c++-build.cpp:(.text+0x6313): undefined reference to `UNSTREAM_STRING(unsigned char const*, long, bool)'
/tmp/ccb5gboe.o:rusthon-c++-build.cpp:(.text+0x6333): more undefined references to `UNSTREAM_STRING(unsigned char const*, long, bool)' follow
/tmp/ccb5gboe.o: In function `init__main__':
rusthon-c++-build.cpp:(.text+0x63ae): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x63e5): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x641c): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x6456): undefined reference to `MAKE_CODEOBJ(_object*, _object*, int, _object*, int, int)'
rusthon-c++-build.cpp:(.text+0x64ed): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x6541): undefined reference to `IMPORT_MODULE(_object*, _object*, _object*, _object*, _object*)'
rusthon-c++-build.cpp:(.text+0x6734): undefined reference to `Nuitka_Function_New(_object* (*)(Nuitka_FunctionObject*, _object**, long, _object*), _object* (*)(Nuitka_FunctionObject*, _object**, int), _object*, PyCodeObject*, _object*, _object*, _object*)'
rusthon-c++-build.cpp:(.text+0x6aa6): undefined reference to `MAKE_FRAME(PyCodeObject*, _object*)'
rusthon-c++-build.cpp:(.text+0x6cd5): undefined reference to `detachFrame(_traceback*, _object*)'
rusthon-c++-build.cpp:(.text+0x715b): undefined reference to `builtin_module'
rusthon-c++-build.cpp:(.text+0x7503): undefined reference to `Nuitka_Function_New(_object* (*)(Nuitka_FunctionObject*, _object**, long, _object*), _object* (*)(Nuitka_FunctionObject*, _object**, int), _object*, PyCodeObject*, _object*, _object*, _object*)'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "./rusthon.py", line 1330, in <module>
    main()
  File "./rusthon.py", line 1219, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "./rusthon.py", line 1058, in build
    subprocess.check_call( cmd )
  File "/usr/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['g++', '-O3', '-fprofile-generate', '-march=native', '-mtune=native', '-I/tmp', '-I/usr/local/lib/python2.7/dist-packages/nuitka/build/include', '/tmp/rusthon-c++-build.cpp', '-o', '/tmp/rusthon-c++-bin', '-pthread', '-std=c++11', '-I/usr/include/python2.7', '-lpython2.7']' returned non-zero exit status 1
```
https://github.com/rusthon/Rusthon/commit/a8c52105271e5081bcee1023abab6cc81bf55080

**Comment by hartsantler** [comment]
above is fixed, but now these errors:
```bash
g++ -O3 -fprofile-generate -march=native -mtune=native -I/tmp -I/usr/local/lib/python2.7/dist-packages/nuitka/build/include /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11 -I/usr/include/python2.7 -lpython2.7
/tmp/rusthon-c++-build.cpp:1734:62: error: ‘NUITKA_COMPILED_MODULE’ was not declared in this scope
/tmp/rusthon-c++-build.cpp:1736:1: error: elements of array ‘Nuitka_MetaPathBasedLoaderEntry meta_path_loader_entries []’ have incomplete type
/tmp/rusthon-c++-build.cpp:1736:1: error: storage size of ‘meta_path_loader_entries’ isn’t known
/tmp/rusthon-c++-build.cpp: In function ‘void initnuitka_build()’:
/tmp/rusthon-c++-build.cpp:1788:62: error: ‘registerMetaPathBasedUnfreezer’ was not declared in this scope
/tmp/rusthon-c++-build.cpp: In function ‘PyObject* get_nuitka_module()’:
/tmp/rusthon-c++-build.cpp:2121:40: error: ‘module___main__’ was not declared in this scope
/tmp/rusthon-c++-build.cpp: In function ‘PyDictObject* get_nuitka_module_dict()’:
/tmp/rusthon-c++-build.cpp:2122:49: error: ‘moduledict___main__’ was not declared in this scope
/tmp/rusthon-c++-build.cpp: In function ‘int main()’:
/tmp/rusthon-c++-build.cpp:2251:2: error: ‘moduledict___main__’ was not declared in this scope
/tmp/rusthon-c++-build.cpp:2252:30: error: unable to deduce ‘auto’ from ‘<expression error>’
```

should just need to define `NUITKA_COMPILED_MODULE` and setup moduledict__main__.

**Comment by hartsantler** [comment]
Nuitka integration may not be as helpful anymore, now that we have our own syntax for calling into the PythonVM and using its C-API.  Pushing this feature back to Rusthon2.0.

**Comment by hartsantler** [comment]
Nuitka integration simplified by compiling a python module that gets packaged with the output tar.
https://github.com/rusthon/Rusthon/commit/52c82b67b975d3f9d8156f2605ce224bfdc08a88

So special calling or build is required.  Closing this issue.
