### ISSUE TITLE
No such file or directory: '/usr/local/bin/fakelibs/sys.py'

### ISSUE THREAD

**Issue by rockdaboot** [rusthon/Rusthon#86]
I just followed the README.md (clone, install) and tried:
```
$ transpile pslint.py --go
Traceback (most recent call last):
  File "/usr/local/bin/transpile", line 1951, in <module>
    main()
  File "/usr/local/bin/transpile", line 1725, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "/usr/local/bin/transpile", line 834, in build
    pyjs = python_to_pythonjs(script, go=True, module_path=module_path)
  File "<string>", line 5658, in python_to_pythonjs
  File "<string>", line 2463, in __init__
IOError: [Errno 2] No such file or directory: '/usr/local/bin/fakelibs/sys.py'
```

Some kind of dependency missing ? Internet search didn't reveal anything... Could you add a few words about dependencies to REAME.md, please ?

**Comment by rockdaboot** [comment]
Also, after installing the Debian package:

```
$ transpile --go pslint.py
Traceback (most recent call last):
  File "/usr/bin/transpile", line 1741, in <module>
    bootstrap_rusthon()
  File "/usr/bin/transpile", line 1716, in bootstrap_rusthon
    import_md( os.path.join(localdir,'src/main.md'), modules=mods )
  File "/usr/bin/transpile", line 341, in import_md
    data = codecs.open(url, 'r', 'utf-8').read()
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/usr/lib/rusthon/src/main.md'

$ ls -la /usr/lib/rusthon/
total 140
drwxr-xr-x   2 root root  4096 Feb 19 11:41 .
drwxr-xr-x 217 root root 77824 Feb 19 11:41 ..
-rwxr-xr-x   1 root root 55985 Nov 11 17:25 rusthon.py
```

**Comment by hartsantler** [comment]
thanks for reporting this bug, the above commit fixes it.

the script you are translating imports the `sys` module, which will fail when you try to compile with this error
```bash
rusthon-go-build.go:4:8: cannot find package "sys" in any of:
	/usr/lib/go/src/pkg/sys (from $GOROOT)
	($GOPATH not set)
```

This is because the Go backend has is lacking wrapper libraries that emulate python's builtins like `os`, and `sys` modules.

**Comment by rockdaboot** [comment]
Now I see

```
$ transpile --go pslint.py 
Traceback (most recent call last):
  File "/usr/local/bin/transpile", line 1951, in <module>
    main()
  File "/usr/local/bin/transpile", line 1725, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "/usr/local/bin/transpile", line 834, in build
    pyjs = python_to_pythonjs(script, go=True, module_path=module_path)
  File "<string>", line 5627, in python_to_pythonjs
  File "<string>", line 2450, in __init__
  File "<string>", line 1800, in visit
  File "<string>", line 5019, in visit_FunctionDef
  File "<string>", line 1800, in visit
  File "<string>", line 5131, in visit_For
  File "<string>", line 1800, in visit
  File "<string>", line 4104, in visit_Print
  File "<string>", line 1800, in visit
  File "<string>", line 4231, in visit_Call
  File "<string>", line 1800, in visit
  File "<string>", line 2775, in visit_GeneratorExp
  File "<string>", line 2833, in visit_ListComp
  File "<string>", line 2861, in _visit_listcomp_helper
AttributeError: 'GeneratorExp' object has no attribute 'go_listcomp_type'
```

How comes that you don't have that ?

**Comment by hartsantler** [comment]
For the Go backend, very little work was put into emulating the standard python build libraries, like `sys` and `os`.

Each target language provides its own builtin libraries that you can use directly to do the same thing that `sys` provides.

**Comment by rockdaboot** [comment]
My intention was to translate python into Go. I read somewhere that rusthon is able to do that, but it failed for me with a very simple python script because of using 'import sys'.

> Each target language provides its own builtin libraries that you can use directly to do the same thing that sys provides.

So what can I do about it - I have absolutely no idea what actions arise from this comment !
Maybe you could give an example, or point me to some detailed description ?
