### ISSUE TITLE
How do imports work?

### ISSUE THREAD

**Issue by mationai** [rusthon/Rusthon#87]
Trying to compile one of the files in https://github.com/rusthon/Rusthon/tree/master/regtests/stdlib to see how import works. Tried json.py. Compiling with `--c++` flag.  It errors:

```
 #include <json>
                ^
compilation terminated.
Traceback (most recent call last):
  File "/usr/local/bin/rusthon", line 1951, in <module>
    main()
  File "/usr/local/bin/rusthon", line 1725, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "/usr/local/bin/rusthon", line 1398, in build
    subprocess.check_call( cmd )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['g++', '-O3', '-fprofile-generate', '-march=native', '-mtune=native', '-I/var/folders/5q/gfmq7wv94gg07l02cq3mxd400000gn/T', '-Wl,-rpath,/usr/local/lib/', '-Wl,-rpath,./', '/var/folders/5q/gfmq7wv94gg07l02cq3mxd400000gn/T/rusthon-c++-build.cpp', '-o', '/var/folders/5q/gfmq7wv94gg07l02cq3mxd400000gn/T/test', '-pthread', '-std=c++11', '-ldl']' returned non-zero exit status 1
```

Is there supposed to be a rusthon json.py I should put somewhere? If so, where are the source for these files and what libs are supported?

**Comment by hartsantler** [comment]
development has moved to the blazescript fork, the c++ backend is upgraded to use c++14, and other new features like C# backend.
