### ISSUE TITLE
Syntax Error on this line: __new__>>+= "\0" + c

### ISSUE THREAD

**Issue by Stoyvo** [rusthon/Rusthon#88]
Code being parsed:
```
    new = ""
    for c in orig:
        new += "\0" + c
    return new
```

```
--------------------------------------------------------------------------------
Syntax Error on this line:
        __new__>>+= "\0" + c
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/transpile", line 1951, in <module>
    main()
  File "/usr/local/bin/transpile", line 1725, in main
    package = build(modules, base_path, datadirs=datadirs )
  File "/usr/local/bin/transpile", line 834, in build
    pyjs = python_to_pythonjs(script, go=True, module_path=module_path)
  File "<string>", line 5627, in python_to_pythonjs
  File "<string>", line 2364, in __init__
  File "<string>", line 1390, in transform_source
  File "<string>", line 1466, in parse_and_fix_code
  File "<unknown>", line 116
    __new__>>+= "\0" + c
              ^
SyntaxError: invalid syntax
```
(^ is under the =)

**Comment by hartsantler** [comment]
To be compatible with javascript and other backends, `new` is a reserved keyword in rusthon.  There should be a better error message, to let you know that it is reserved.
